### ISSUE TITLE
Interface scope still need to be cast then retriewing

### ISSUE THREAD

**Issue by neworld** [SalomonBrys/Kodein#102]
I have such scope:
```kotlin
interface DatabaseScope {
    val scopeRegistry: ScopeRegistry

    companion object : Scope<DatabaseScope> {
        override fun getRegistry(context: DatabaseScope): ScopeRegistry {
            return context.scopeRegistry
        }
    }
}
```
I have various contexts for this scope (Controller, Worker). However, it doesn't work without the cast. This is a very similar problem with #33, but only for an interface.

**Comment by SalomonBrys** [comment]
Scopes have deeply evolved in Kodein 5.0.
Could you try it and see if you have the same problem ?

**Comment by neworld** [comment]
It is working on 5.0.

BTW, is really nice I can put scope on whole `KodeinAware`  and don't need care abotu scopes inside the class
