### ISSUE TITLE
Wrong imports in 5.0 android demo?

### ISSUE THREAD

**Issue by dutchmo** [SalomonBrys/Kodein#109]
The imports in the 5.0 demo are 
`import org.kodein.*`
but shouldn't they be 
`import org.kodein.generic.*`

with the new packaging system?
or am I missing something?

Excited about 5.0!

**Comment by SalomonBrys** [comment]
No you're totally right. I forgot about that.
Sorry.

Also, by running the app, I found a bug, so I'll be publishing Beta 3 today.

Thanks a lot!

**Comment by SalomonBrys** [comment]
Kodein 5.0 beta 4 has been published ;)
