### ISSUE TITLE
Kodein does work on Android as-is. but it's better use KodeinAware in Android?

### ISSUE THREAD

**Issue by cuichanghao** [SalomonBrys/Kodein#111]
"Kodein does work on Android as-is."

so i put kodein to global value in DI.kt
because i can use simply kodein.

```
lateinit var kodein: Kodein

object DI {
    fun initKodeIn(app: App) {
        kodein = Kodein {
            import(DIModule.getApplicationModule(app))
            import(DIModule.apiModule)
        }
    }
}
```

but this kodein is static value in jvm.
and i found below warning, static value may be lost.

[warning-do-not-place-android-context-classes-in-static-fields-this-is-a-memory](https://stackoverflow.com/questions/37709918/warning-do-not-place-android-context-classes-in-static-fields-this-is-a-memory
)

it's better use KodeinAware in Android?

```
class MyApp : Application(), KodeinAware {
	override val kodein by Kodein.lazy { 
	    /* bindings */
	}
}
```

**EDIT**
i found document
- Configuring on the go (Configurable Kodein)
- The god complex: One True Kodein
- Being globally aware

globally aware may occur performance hit ?

**EDIT**
I want use global aware because want use Kotlin object class as singleton.

**Comment by SalomonBrys** [comment]
Github issues are for issues about the library itself.
For question about its usage, please use StackOverflow.

Now that this is out of the way, let me answer your question ;)

There are no real performance cost of using a static Kodein, nor there are using `Kodein.global` with the `kodein-conf` module.
**However**, using a static is an anti-pattern:
- In Android, as you found out
- In development as a whole as it renders testability more complicated (you need to reconfigure the global kodein between each test, and you cannot run tests in paralel).
That said, if you understand these drawbacks, using a static Kodein, or `Kodein.global` (which is, in essence, a static Kodein) is a valid choice.

The `KodeinAware` Application class is the pattern I personally recommend, with **and** without the `kodein-android` module.

The sentence "Kodein does work on Android as-is" refers to the fact that you don't need to use the `kodein-android` module which adds more features to Kodein that Androiid specifics.

**Comment by cuichanghao** [comment]
thank you.
