### ISSUE TITLE
Default dependency for not registered tag

### ISSUE THREAD

**Issue by Dwite** [SalomonBrys/Kodein#112]
Hello, 

I'm curious is it possible to provide default implementation if there is no dependency with the requested tag?

```
val kodein = Kodein {
    bind<Dice>() with factory { sides: Int -> DefaultDice() } 
    bind<Dice>("DnD10") with provider { Dice10() } 
    bind<Dice>("DnD20") with singleton { Dice20() } 
}
```

Then when we request Dive with tag **"DND30"** `DefaultDice` is returned

**Comment by SalomonBrys** [comment]
No, it's not.
The tag is supposed to be used as a binding differntiator, not a factory argument.

Sorry ;)
