### ISSUE TITLE
Question - Generic type binding

### ISSUE THREAD

**Issue by brezinajn** [SalomonBrys/Kodein#115]
Is some pattern like this possible?

    Controller<T>(repository: Repository<T>)

    …

    bind<Repository<T>>() with singleton{ Repository<T>(/*something*/) }
    bind<Controller<T>>() with singleton{ Controller<T>(instance()) }

    …

    val userRepository: Repository<User> = kodein.instance()

Or do I need to provide binding for every type? (```Controller<Foo>, Controller<Bar>, Repository<Foo>, Repository<Bar>```).
Thanks

**Comment by SalomonBrys** [comment]
No, it is not possible,
It would mean a different singleton for each value of T, which would pose a lot of problems very hard to solve.

**Comment by brezinajn** [comment]
> It would mean a different singleton for each value of T

Yep, that was the point. 
Anyway thank you for fast response :)
