### ISSUE TITLE
Kodein.instante() is returning KodeInProperty instead of the expected type

### ISSUE THREAD

**Issue by guitcastro** [SalomonBrys/Kodein#116]
I am using kodein 5.0 Beta, and trying to do a simple injection:

<img width="716" alt="screen shot 2018-03-22 at 13 53 40" src="https://user-images.githubusercontent.com/1149991/37785330-a66e7a6c-2dd8-11e8-97d1-b779cfcb2283.png">

But kodein.instance is not returning my expected type ...

**Comment by brezinajn** [comment]
use 
```Kotlin
var viewModfelFactory: ViewModelProvider.Factory by kodein.instance()
```
