### ISSUE TITLE
kodein.instance() returns KodeinProperty  

### ISSUE THREAD

**Issue by stasbar** [SalomonBrys/Kodein#119]
Hello.
I'm following the documentation, and I can't reproduce working code.
Using org.kodein:kodein-generic-jvm:5.0.0-beta5
```
import org.kodein.Kodein
import org.kodein.generic.instance

class Database (val kodein: Kodein){
    fun makeConnection() = DriverManager.getConnection(kodein.instance("dbPath")) 
}
```

in the code above the compiler, yield on `kodein.instance("dbPath")` that:

> Type Inference failed. Expected type mismatch: Required: String! Found: KodeinProperty<???>

How to dispatch this KodeinProperty to my String ?

**Comment by streetsofboston** [comment]
One option, using `.direct`:
```
import org.kodein.Kodein
import org.kodein.generic.instance

class Database (val kodein: Kodein){
    fun makeConnection() = DriverManager.getConnection(kodein.direct.instance("dbPath")) 
}
```

or this using `by`:

```
import org.kodein.Kodein
import org.kodein.generic.instance

class Database (val kodein: Kodein){
    fun makeConnection(): Connection { 
        val path by kodein.instance<Path>("dbPath")
        return DriverManager.getConnection(path) 
    }
}
```
(I took a guess at the type-names `Path` and `Connection` 😄 )

**Comment by stasbar** [comment]
It worked. But, I will stick with 4.0 since `kodein.instance` is much cleaner 👍

**Comment by bdavisx** [comment]
If you're still on 4.x and would prefer to be on 5.x, you can do something like the following in 5.x to get back the direct instance functionality:
```
// define an extension function on a Kodein instance to get an instance directly instead of 'property by'
inline fun <reified T : Any> Kodein.instanceDirect(tag: Any? = null) = direct.Instance<T>(generic(), tag)

// use it like this
class SomeClass(val kodein: Kodein) {
    fun doSomething() {
        val dependency: DependencyClass = kodein.instanceDirect()
    }
}
```
