### ISSUE TITLE
Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.github.salomonbrys.kodein.android.KodeinApplication

### ISSUE THREAD

**Issue by westito** [SalomonBrys/Kodein#12]
After redeploy application upon code change, the application crashes. The latest android, gradle, kotlin, etc.

**Comment by SalomonBrys** [comment]
Can you check the following?

 * Your application class in declared in your manifest (<Application name="your.app.class">)
 * Your application class implements the `KodeinApplication` interface

**Comment by westito** [comment]
It works in the most case. Just drops random excpetions upon new deploy. But I think I solved. It is not your code. Android Studio instant run causes the issue.

**Comment by SalomonBrys** [comment]
Thanks for the report ;)

**Comment by saiday** [comment]
@westito hi, could you explain more why "random exceptions upon new deploy" is caused by Instant Run?

I have the same issue.
