### ISSUE TITLE
Proper way to inject Android Context.

### ISSUE THREAD

**Issue by matoushybl** [SalomonBrys/Kodein#15]
Hi, what is the proper way to inject Android Context?

**Comment by SalomonBrys** [comment]
Hi,
it's currently not possible, nor should it be.
By definition, stocking a Context should only be done with extreme care to prevent memory leak.

Furthermore, the Context depends... on the context. Whether you want the Activity, a Service, the Application context, etc. depends on the location and purpose of your code.

At most, you could register the Application object (which is a Context) in your kodein bindings ;)
