### ISSUE TITLE
import and Module are too tightly coupled

### ISSUE THREAD

**Issue by dalewking** [SalomonBrys/Kodein#16]
import is tightly coupled to the Module class which is a final class. I would like to be able to define my own class to be imported primarily to be able to pass arguments to the class (e.g. pass the Android Application instance to the module).

import should not take a Module instance directly, it should take an interface that Module implements. What I would really love to be able to just say is that Module implements Kotlin.Builder.() -> Unit, but unfortunately extension function types cannot be used as supertypes.

So this is what seems to make sense to me. Define a `Kodein.Import` interface:

    interface Import : () -> Kodein.Builder.() -> Unit

Then import would be changed to use that interface:

    fun import(import: Import) = import().invoke(this)

Module then is only one possible implementation of the interface:

    class Module(val init: Kodein.Builder.() -> Unit) : Import
    {
        override fun invoke() = init
    }

Then I could define my own class types to import:

    class MyModule(val application: Application) : Kodein.Import
    {
        override fun invoke() : Kodein.Builder.() -> Unit =
        {
            todo()
        }
    }

which I can then use as:

    import(MyModule(theApplication))

**Comment by SalomonBrys** [comment]
You can currently do what you're asking:

```
fun MyModule(val application: Application) = Kodein.Module {
    bind<Application>() with instance(application)
    /* other bindings */
}
```
