### ISSUE TITLE
Compiles and works with Javascript?

### ISSUE THREAD

**Issue by jvskriubakken** [SalomonBrys/Kodein#22]
Hi!

I'm looking for a injection-like framework for Kotlin that would compile to Javascript.

Does your "Kodein" framework do that?

Regards,
Jørund

**Comment by czyzby** [comment]
Not an expert by any means, but just wanted to say that it's highly unlikely. Kodein uses JVM-specific APIs (like `java.lang.Class`, `java.lang.reflect.Type`), which are not expected to work with Kotlin-JS.

**Comment by SalomonBrys** [comment]
Hi, at the moment, Kodein is neither supported nor tested on JavaScript.
As stated by @czyzby, it uses JVM-specific APIs which almost ensures that it will not work.

When JS is anounced as officially supported with a stable API, I might consider supporting JS, but not before.
