### ISSUE TITLE
Missing documentation for proguard

### ISSUE THREAD

**Issue by masc3d** [SalomonBrys/Kodein#23]
Kodein apparently requires `-keepattributes Signature`, would be great if it's documented.

**Comment by SalomonBrys** [comment]
Didn't know that (I don't use Proguard). Will document straight away. Thanks a lot :)

**Comment by SalomonBrys** [comment]
Done, thanks again for the report ;)

**Comment by masc3d** [comment]
Thank you for providing the only dependency injection that currently makes sense for most Android projects )
