### ISSUE TITLE
Currying a factory with a more specific type

### ISSUE THREAD

**Issue by dynaxis** [SalomonBrys/Kodein#25]
Using 3.0.0-beta6.

I have the following binding:

```
bind() from factory { element: Element ->
   EntityRelatedNameBuilder(kodein, element)
}
```

And when I do the following, I got a `Kodein.NotFoundException`:

```
val names: EntityRelatedNameBuilder = with(element /* a TypeElement that is a subtype of Element */)
   .instance()
```

Isn't this supposed to work properly? I had to add an explicit type parameter to the `with` as follows:

```
val names: EntityRelatedNameBuilder = with<Element>(element).instance()
```

**Comment by SalomonBrys** [comment]
Yes, this is as expected.

For now ;)

I'll leave this open as a possibility of enhancement.

**Comment by SalomonBrys** [comment]
Good news!

I've tackled this issue in 5d226da, which will be part of version `3.1.0`, which will be published in the next few days :smile:
