### ISSUE TITLE
Remove dependencies from Kodein-Android

### ISSUE THREAD

**Issue by tsuharesu** [SalomonBrys/Kodein#3]
I had to remove this dependencies for my project to compile again

```groovy
compile('com.github.salomonbrys.kodein:kodein-android:2.1.0') {
    exclude module: 'support-v4'
    exclude module: 'android'
}
```
Take a look if this can be removed from the project, or add this lines on the import statement on the README

**Comment by SalomonBrys** [comment]
This should be corrected:

```
compile 'com.github.salomonbrys.kodein:kodein-android:2.1.1'
```

Thanks a lot for the report :smile:
