### ISSUE TITLE
Question: Providing context to nested injection

### ISSUE THREAD

**Issue by stepango** [SalomonBrys/Kodein#32]
```
bind<FirebaseAnalytics>() with factory { ctx: Context -> FirebaseAnalytics.getInstance(ctx) }
bind<Tracker>() with singleton { FireBaseTracker(instance()) }
```
Code above does not work obviously, with and without context.

but i still want to inject Tracker via singleton, using ApplicationContext, how i could do it in this situation? is it possible?

**Comment by SalomonBrys** [comment]
Where do you define the Kodein instance / module defining this singleton ?

**Comment by stepango** [comment]
Kodein instance defined in Android Application class

**Comment by SalomonBrys** [comment]
Well then:

```kotlin
class MyApplication : Application(), KodeinAware {

    override val kodein by Kodein.lazy {

        bind<FirebaseAnalytics>() with factory { ctx: Context -> FirebaseAnalytics.getInstance(ctx) } // <1>

        bind<FirebaseAnalytics>("app") with provider { factory<Context, FirebaseAnalytics>().invoke(this@MyApplication) } // <2>

        bind<Tracker>() with singleton { FireBaseTracker(instance("app")) } // <3>

    }
}
```

`<1>`: Binds `FirebaseAnalytics` to a factory with `Context`.

`<2>`: Binds `FirebaseAnalytics` with the tag "app" to a provider that delegates the creation to the previously defined factory and providing it the application context.

`<3>`: Binds the `Tracker` to a `FireBaseTracker` constructed with the `FirebaseAnalytics` retrieved with the tag "app" (and therefore uses the provider, not the factory).

I hope this answers your question ;)

**Comment by deviant-studio** [comment]
How about this?
```kotlin
fun mainComponent(app: App) = Kodein.lazy {
    bind<Context>() with instance(app)
    bind<FirebaseAnalytics>() with singleton { FirebaseAnalytics.getInstance(instance()) }
}
```
and call it from the App instance.
