### ISSUE TITLE
Android Scopes Need to Be Cast To Base Class When Retrieving

### ISSUE THREAD

**Issue by eygraber** [SalomonBrys/Kodein#33]
If I have the following `Activity`

```
class TestActivity : Activity() {
  val kodein = Kodein {
    bind<Any>() with activitySingleton { Any() }
  }

  private val any1: Any = kodein.with(this).instance()
  private val any2: Any = kodein.with(this).instance()

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    Log.e("TEST", "$any1 $any2")
  }
}
```

I get an error:

> java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.test/com.test.TestActivity}: com.github.salomonbrys.kodein.Kodein$NotFoundException: No factory found for bind<Object>() with ? { TestActivity -> ? }
                                                                 Registered in Kodein:
                                                                         bind<Object>() with scopedSingleton(activityScope) { Activity -> Object } 

If I change the retrieval to:

```
  private val any1: Any = kodein.with(this as Activity).instance()
  private val any2: Any = kodein.with(this as Activity).instance()
```

it works.

**Comment by eygraber** [comment]
Actually, it looks like this happens any time `with` is called. Subtypes need to be explicitly cast to the factory argument.

**Comment by SalomonBrys** [comment]
This is the exact problem as #25. I need to include some sort of warning to the documentation about that.

A temporary fix would be to include a `withActivity` function that does the cast.

**Comment by SalomonBrys** [comment]
Closing in favour of #25
