### ISSUE TITLE
Can't inject in a service

### ISSUE THREAD

**Issue by greenspand** [SalomonBrys/Kodein#38]
I am new to Kodein, so maybe I am doing something wrong. 
I have a service where I implement the `KodeinInjected` and in `onCreate` inject the ` inject(appKodein())`
I try to call an instance of  `val sharedPrefs: SharedPreferences by withContext(this).instance()`
but I get a null pointer  `java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.salomonbrys.kodein.KodeinInjector$TInjector com.github.salomonbrys.kodein.KodeinInjector.getTyped()' on a null object reference`
How can I import my dependency in a service considering this works in an activity already.
Thx. And by the way awesome library. We are using it in production already.

**Comment by SalomonBrys** [comment]
Hi @greenspand.
Could you post the entire stack trace ?

**Comment by greenspand** [comment]
Hi @SalomonBrys, I found the problem. I think I placed the moethod     `override val injector = KodeinInjector() ` too far down, like after `onCreate()` and this is why it crashed.                                                          Now it's right at the begining of the service like this, and it super works.
```
class MQTTService() : Service(), MqttCallback, KodeinInjected {
    override val injector = KodeinInjector()
    val rxBus: RxBus by instance()
}
```

**Comment by greenspand** [comment]
But it is good to know that the position of the method matters. Thx for your hard work. I really love your liobrary. It is far more clear and compossable than Dagger2, without the ceremony and all that Jazz.

**Comment by SalomonBrys** [comment]
Glad you could find your error,
thanks for the compliment ;)
