### ISSUE TITLE
Can I use lazy loading when calling  by instance()

### ISSUE THREAD

**Issue by greenspand** [SalomonBrys/Kodein#39]
It is more a question than an issue. I am not sure if the called dependency with `by instance()` are called lazy when actually used or when the app starts

**Comment by greenspand** [comment]
Kind opf like in Dagger2 
```
@Inject 
Lazy<Grinder> lazyGrinder;
```

**Comment by sorinirimies** [comment]
My question was answered by this: override val kodein by Kodein.lazy

**Comment by greenspand** [comment]
My question was answered by this: override val kodein by Kodein.lazy
