### ISSUE TITLE
Android injector documentation teaches wrong

### ISSUE THREAD

**Issue by tsuharesu** [SalomonBrys/Kodein#4]
I was having a lot of trouble trying to figure why Kodein was having problems on my app, turns out the docs are telling different things than the correct.

https://github.com/SalomonBrys/Kodein#using-an-injector
Here you say to use `=` but the correct way to get the instance is using `by` - as used on the Android Demo.

**Comment by SalomonBrys** [comment]
Soooo sorry about that :flushed:.
