### ISSUE TITLE
Access original instance from within overriding statement

### ISSUE THREAD

**Issue by dimorinny** [SalomonBrys/Kodein#43]
In tests I want to wrap real object with some test logic and pass wrapped instance to application.

Now for this case, I also provide implementation of object and use it only in override-provider, so it looks like this:

```
// Module in real Application
...
bind<AvsDoActionExecutor>() with singleton {
    instance<AvsDoActionExecutorImpl>()
}

bind<AvsDoActionExecutorImpl>() with singleton {
    AvsDoActionExecutorImpl(
        // something
    )
}
```

```
// Module with override flag in test Application
...
bind<AvsDoActionExecutor>() with singleton {
    TestLogicWrapper(instance<AvsDoActionExecutorImpl>())
}
```

Are there ways to do it natively in Kodein 2.8.0? Is there any way to access original instance from within overriding statement?

**Comment by SalomonBrys** [comment]
No, there's no better way, sorry.

Though, for this use case, I wouldn't bind directly `AvsDoActionExecutorImpl` but create a second bind of `AvsDoActionExecutor` with a tag.

```
// Module in real Application
...
bind<AvsDoActionExecutor>() with singleton {
    instance<AvsDoActionExecutor>("actual")
}

bind<AvsDoActionExecutor>("actual") with singleton {
    AvsDoActionExecutorImpl(
        // something
    )
}
```
```
// Module with override flag in test Application
...
bind<AvsDoActionExecutor>() with singleton {
    TestLogicWrapper(instance<AvsDoActionExecutor>("actual"))
}
```

I realize this is not ideal. However, the branch 2.x is not developped anymore (unless for bug fixes).

In branch 3.x, allowing overrides to access the overriden binding is an interesting idea. I'm not sure how much it would complicate the code. I'll think on it ;)

**Comment by SalomonBrys** [comment]
I'm happy to report that access to overrides will be part of Kodein 3.2.0.

Your use case will be as simple as:

```
// Module in real Application
...
bind<AvsDoActionExecutor>() with singleton {
    AvsDoActionExecutorImpl(
        // something
    )
}
```

```
// Module with override flag in test Application
...
bind<AvsDoActionExecutor>() with singleton {
    TestLogicWrapper(overriddenInstance<AvsDoActionExecutor>())
}
```

Thanks for the great feature idea ;)

Salomon.

**Comment by dimorinny** [comment]
It's great. Thanks 👍
