### ISSUE TITLE
CurriedInjectorFactory instance and provider Methods Expect an Extra Type Parameter

### ISSUE THREAD

**Issue by eygraber** [SalomonBrys/Kodein#44]
All CurriedInjectorFactory methods expect there to be 2 type parameters (A and T : Any) when there should only be one (T : Any) because these are not factory methods.

**Comment by SalomonBrys** [comment]
Corrected in 347e8fa98dbd451ada469d3368c1c101a7ee0923

Thanks for the report ;)
