### ISSUE TITLE
Kodein in an Android Library

### ISSUE THREAD

**Issue by shyamvala** [SalomonBrys/Kodein#45]
Hi,

I have been trying to build a android library using Kotlin and came across Kodein for DI. A lot of examples in the documentation are based on using it for an Android Application where we make the Application class KodeinAware. I am just curios if this works the same way even if I am creating and Android Library where I don't have an application class but a generic configuration class that will be called during the initialization phase of the Client that is going to use the library. The library will house Broadcast Receivers, Activities along with other generic classes.

I wanted to quickly ask this question before I go start hooking it up.

**Comment by SalomonBrys** [comment]
Hi,
Using `KodeinAware` is just a suggestion, it is not mandatory tp use `Kodein`.

The only mandatory thing is a way to access a `Kodein` instance.

- If your library adds sone configuration to Kodein, it should provide a `Kodein.Module`.
- If your library needs to retrieve instances (or providers / factories), it should provide a way to give it a `Kodein` instance.
