### ISSUE TITLE
Android: KodeinInjector and appKodein()

### ISSUE THREAD

**Issue by mradzinski** [SalomonBrys/Kodein#46]
On Android, Is it possible to implement ```KodeinInjector``` on a class that does not extend from any other Android class such as Activity, Fragment, etc?

To give this question more context: I use an MVP architecture, so my Presenter does not implement/extend anything Android related (thus increasing testability). Normally Presenters would be the most "injected" classes since they're in charge of all the business logic, so, I was wondering if there's a way of injecting those presenters using Kodein. So far I tried with a KodeinInjector, but I have no access to ```appKodein``` nor the Kodein instance declared in the Application class.

**Comment by SalomonBrys** [comment]
I assume you are talking about `KodeinInjected` ?

Your Presenter should take as a constructor parameter a Kodein instance.

Please use Slack or StackOverflow if you are in need of help or support ;). These issues are for, well, issues.

Salomon.
