### ISSUE TITLE
Multiton support

### ISSUE THREAD

**Issue by fvasco** [SalomonBrys/Kodein#47]
In provided example RandomDice provider creates a new instance for every invocation, and DataSource is a singleton.

Kodein misses of "singletonProvider", a function to lazy create a parametrized singleton instance.

Further enhancement: should be nice to define soft/weak singleton to avoid memory leak, but however this isn't my use case.

**Comment by SalomonBrys** [comment]
Can you be more specific:

 * What exactly would `singletonProvider` do that `singleton` does not ?
 * What is a "soft/weak singleton" ?

Thanks for your feedback ;)

Salomon

**Comment by fvasco** [comment]
Following you example I need to define a provider for RandomDice with parametric side number, but in my case create RandomDice is very expensive and I need to create a given dice only one time.

First time I call "instance(6)" Kodein make a new RandomDice(6), the other times Kodein provides always first instance.
You can search for "Multiton design pattern".

Both singleton or multiton can be implemented using Weak or Soft references. When  the instance isn't referenced anymore then Kodein removes it from its internal association map and recreates a new one when requested: this doesn't violate singleton contract (only one instance), allows to reduce memory impact and exposes to discard singleton state in any time.
Lazy pointers for singleton require some attention but this isn't my case.

**Comment by SalomonBrys** [comment]
Hi Francesco,
these are both valid ideas, thanks a lot ;)

I'll let this issue open for the time being. I currently don't really have the time to implement those, but I'll think about it when I will ;)

Salomon.

**Comment by fvasco** [comment]
My workaround:

    val values = HashMap<Key, Value>()
    bind<Value>() with factory { key: Key ->
        synchronized(values) {
            values.getOrPut(key) { Value(key) }
        }
    }

**Comment by SalomonBrys** [comment]
Thanks for the feedback, multitons and refSingletons will both appear in version `3.3.0` :)

**Comment by fvasco** [comment]
Thanks for your support ;)
