### ISSUE TITLE
"UninjectedException: Value has not been injected" after orientation change

### ISSUE THREAD

**Issue by Bodo1981** [SalomonBrys/Kodein#50]
When I use an kodein activity and and kodein fragment, the first start of the activity works perfect. But if i rotate the device, the fragment gets recreated before onCreate of the the activity is finished.

That  means that the kodein value is not injected when the fragment needs it.

This could be easily fixed if in all kodein activities you call initializeInjector **BEFORE** super.onCreate(savedInstanceState)

-> a workaround for the moment is to use the interface versions and call this function in the activities yourself before super.onCreate(savedInstanceState)

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initializeInjector()
}
```

should be changed to

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        initializeInjector()
        super.onCreate(savedInstanceState)
}
```

in KodeinActivity, KodeinFragmentActivity and KodeinAppCompatActivity

**Comment by eygraber** [comment]
The only question with fixing this is can anything go wrong by initializing the injector before `onCreate`?

Also, it might be more explicit to do:

```
if(savedInstanceState == null) {
    initializeInjector()
    super.onCreate(savedInstanceState)
}
else {
   super.onCreate(savedInstanceState)
   initializeInjector()
}
```

unless there's truly no downside to always initializing the injector before `onCreate`.
