### ISSUE TITLE
Can Kodein bind a factory with more than one argument?

### ISSUE THREAD

**Issue by lalunamel** [SalomonBrys/Kodein#60]
Hello!

I'd like to bind a `factory` in my `KodeinModule`.
I'd also like this factory to take arguments.

I have successfully created a factory that takes one argument, but when I try to add more the compiler complains that there's no `with` that takes varargs.

The code that produced that error looks something like the following:

#### Binding
```
bind<Cat>() with factory { name: String, color: String, hatesMondays: Boolean ->
    Cat(name, color, hatesMondays)
}
```
#### Using
```
class Comic : KodeinGlobalAware {
  val garfield: Cat = with("Garfield", "Orange", true).instance()
}
```

With the error appearing on the first line of the above code snippet.

What can I do to create a factory that takes multiple arguments?

**Comment by lalunamel** [comment]
Additionally, I passed arguments (using a triple) to my factory incorrectly because I am dumb and the docs don't spell it out in big bold letters.

This is what I did instead:
```
class Comic : KodeinGlobalAware {
  val garfield: Cat = instance(Triple("Garfield", "Orange", true))
}
```

It would be nice if the docs were organized so that sections on binding and sections on retrieving were right next to each other.

After reading [the section on binding factories](https://salomonbrys.github.io/Kodein/#_factory_binding) and arguments, my next question was "How do I pass arguments?"

**Comment by SalomonBrys** [comment]
You cannot pass more than one argument to a factory. It is a limitation that will not be lifted due to how the core of Kodein works.

Whate you are looking for is:

```kotlin
class Comic : KodeinGlobalAware {
  val garfield: Cat = with(Triple("Garfield", "Orange", true)).instance()
}
```

**Comment by joelshea** [comment]
This should be better documented.  It took me a long time to find this issue, which seems to be the only place this limitation is mentioned.
