### ISSUE TITLE
FullTypeStringer fails on a type with no package

### ISSUE THREAD

**Issue by kailan** [SalomonBrys/Kodein#61]
My tests aren't in a package, and this makes the type stringer fail. It's an easy fix but I'm unable to get IntelliJ to load Kodein properly.

https://github.com/SalomonBrys/Kodein/blob/master/kodein-core/src/main/kotlin/com/github/salomonbrys/kodein/typeDisp.kt#L82

**Comment by SalomonBrys** [comment]
I'll fix this on the next version of Kodein 3 & 4.
Thanks for the report :)

**Comment by SalomonBrys** [comment]
BTW, to load Kodein in IDEA, you should disable the JS or Android projects in settings.gradle.
Kotlin + JS + Android is just too much for IDEA :)

**Comment by kailan** [comment]
Awesome, thanks for the help 👌

**Comment by SalomonBrys** [comment]
I've updated the sources of Kodein 4 so that IDEA should be able to load the project ;)

**Comment by SalomonBrys** [comment]
Version `3.4.1` & `4.0.0-beta2` are fixed and uploaded ;)
