### ISSUE TITLE
Include sources in jars

### ISSUE THREAD

**Issue by eygraber** [SalomonBrys/Kodein#62]
Because there are no sources in the jars, opening Kodein classes in Android Studio just shows semi-decompiled kotlin:

```
// IntelliJ API Decompiler stub source generated from a class file
// Implementation of methods is not available

package com.github.salomonbrys.kodein.android

public val androidModule: com.github.salomonbrys.kodein.Kodein.Module /* compiled code */

@android.annotation.SuppressLint public fun autoAndroidModule(app: android.app.Application): com.github.salomonbrys.kodein.Kodein.Module { /* compiled code */ }

@android.annotation.SuppressLint private fun defineAndroidModule(): com.github.salomonbrys.kodein.Kodein.Module { /* compiled code */ }
```

**Comment by SalomonBrys** [comment]
The [sources jar](https://repo1.maven.org/maven2/com/github/salomonbrys/kodein/kodein-core/4.0.0/kodein-core-4.0.0-sources.jar) is available along the [binary jar](https://repo1.maven.org/maven2/com/github/salomonbrys/kodein/kodein-core/4.0.0/kodein-core-4.0.0.jar).

I've just tested in IntelliJ IDEA, the sources do appear correctly (even with comments).

I have no idea why it is not showing them properly on your Idea :(

**Comment by rsajob** [comment]
[kodein-android-4.1.0-sources.jar](https://repo1.maven.org/maven2/com/github/salomonbrys/kodein/kodein-android/4.1.0/kodein-android-4.1.0-sources.jar) is empty

**Comment by eygraber** [comment]
@SalomonBrys it looks like the source jars are still empty for the android libraries.

**Comment by lamba92** [comment]
Yep, still empty today on android!
