### ISSUE TITLE
Android Module and KodeinGlobal

### ISSUE THREAD

**Issue by InNoobWeTrust** [SalomonBrys/Kodein#63]
I tried to imitate the bindings of android module in my Kodein Global. For example:

```kotlin
bind() from ProviderBinding(erased()) { ctx().getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager }
```

In order to avoid momory leak, I made it like this:

```kotlin
bind<ConnectivityManager >() with instance(this@MyApp.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager )
```

The code above didn't work, I print the bindings out and this binding exists, I also try to null-check the instance from Kodein.global and it is not null but when I try something like:

```kotlin
Kodein.global.instance<ConnectivityManager >().activeNetworkInfo.isConnected
```

my app crash and stack trace said that I tried to call these function on a null reference.

Howerver, when I change the code to this and explicitly cast it at retrieve time, it's ok:
```kotlin
bind<Any>("connectivity") with instance(this@MyApp.getSystemService(Context.CONNECTIVITY_SERVICE))
```

I don't know if I'm doing anything wrong. I wonder why it become null just when I call a function on it and not when I check if it is null. Another question is that if it is null at binding time, why does it run without yielding any error until I retrieve the faulty binding?

P/S: Sorry if I said something stupid (I just started with android recently) or any typo (English's not my native language). Hope someone help me with this or even make an android module exclusively for Kodein Global (of course, with some usage note to avoid leaking memory)

**Comment by SalomonBrys** [comment]
Can you be more specific about where / how you are binding in Kodein.global ?

**Comment by InNoobWeTrust** [comment]
All the binding is in onCreate() method of the Application class. I also retrieve the binding in some global Kotlin objects, but I'm pretty sure I only access them after the application is created. I notice the problem when I tried to use autoAndroidModule with Kodein.global and retrieve it in an OkHttp interceptor. Below is the faulty code snippet:

```kotlin
bind<OkHttpClient>() with singleton {
    instance<OkHttpClient>("default")
        .newBuilder()
        .cache(Cache(htmlCacheDir, htmlCacheSize))  
        .addNetworkInterceptor(ForceCacheInterceptor(  
            maxAge = 60L,  
            expireHeader = false  
        ))  
        .addInterceptor { chain ->  
            chain.proceed(chain.request().run {  
                if ((instance<ConnectivityManager>().activeNetworkInfo.isConnected) {  
                    this  
                } else {  
                    newBuilder().header(  
                        "Cache-Control",  
                        "public, only-if-cached, max-stale=2419200"  
                    ).build()  
                }  
            })  
        }  
        .build()  
}
```
The if-check inside the second interceptor always fall to the false case, not yielding any error. I try to check if I'm doing something wrong with the binding by retrieving ConnectivityManager and print the check right after `addConfig` and found the strange behaviour. I end up using the ugly work-around like in first post.

**Comment by InNoobWeTrust** [comment]
I notice I type a wrong parenthesis in first comment, edited and also fixed the format so it won't hurt your eye. Sorry I don't know the proper markdown syntax for code formatting earlier when I first comment.

**Comment by SalomonBrys** [comment]
Well, if `instance<ConnectivityManager>().activeNetworkInfo.isConnected` does not crash and yields false, that it cannot be an error in Kodein.

`bind<Any>()` is a *really* bad practice !

**Comment by InNoobWeTrust** [comment]
At the time, `bind<Any>()` is the only work-around I can think of. It's really bad practice but I haven't found another way, do you have any advice on this?

I browse through the document many times and haven't found a clue why I get this behaviour. Under same testing condition (on my real phone, nexus 6), if I retrieve as `Any` and cast it to appropriate type it's fine, if casting explicitly at binding time it always yields false no matter what.

If you have time please give the document a bit more details about global Kodein so maybe I can find the problem in my code. I think I misunderstand something important about `AndroidModule` so I mimic it in the wrong way (I barely copy-paste the code to my own module).
