### ISSUE TITLE
Multiton bindings for  jx @Inject field

### ISSUE THREAD

**Issue by softkot** [SalomonBrys/Kodein#72]
For any KodeinInjected class it is safe to use fileds like 

`val logger: AppLogger by withClass().instance()`

with proper multiton bindind like 

`bind<AppLogger>() with multiton { cls: Class<*> -> AppLogger(cls.simpleName)   }`

but i can't find solution to get multiton bindings for jx injections for simple POJO classes like 

```
class Worker {
   @Inject lateinit var logger: AppLogger
}
```
I am trying 

```
val worker=Worker()
kodein.jx.inject(worker)
```

and got an exception 

```
...
No provider found for bind<AppLogger>() with ? { ? }
    Registered in Kodein:
        bind<AppLogger>() with multiton { Class<*> -> AppLogger } 
....
```

Is there any workaround?

**Comment by SalomonBrys** [comment]
You need to inject the factory function:

```
@Inject @FactoryFun lateinit var loggerFactory: (Class<*>) -> AppLogger
val logger: AppLogger by lazy { loggerFactory(javaClass) }
```

Note that JxInject exists to be temporary in a project, and to facilitate the move from a JSR-330 based DI framework to Kodein.
