### ISSUE TITLE
Injection via delegate

### ISSUE THREAD

**Issue by Redrield** [SalomonBrys/Kodein#73]
I think that a really nice thing that can be done in Kotlin when it comes to dependency injection is that dependencies can be injected with delegates. I made a small thing that works like this, and essentially, this is what it would look like

```Kotlin
fun main(args: Array<String>) {
    Injekt.configure {
        bind<DataSource> to {
            // get a data source here.
        }
    }
}

// OtherFile.kt
class OtherFIle {
    val ds: DataSource by inject()

}
```

The syntax doesn't have to be exactly like that, but I feel like something similar to that, where you can get dependencies with a delegate instead of passing a singular kodein instance to every class would be nice.

**Comment by SalomonBrys** [comment]
Hi,
have a look at https://salomonbrys.github.io/Kodein/#_the_god_complex_one_true_kodein

Salomon.
