### ISSUE TITLE
hwo to two parameter

### ISSUE THREAD

**Issue by yiyinying** [SalomonBrys/Kodein#76]
data class User(private val name: String,
                private val sex:String)

but this is error

private val kodein = Kodein {
        bind<User>() with factory { name: String, sex: String -> User(name, sex) }
}

hwo to work

**Comment by SalomonBrys** [comment]
A factory can have only one parameter.

In your case, it could be a `Pair`:

```
private val kodein = Kodein {
    bind() with factory { pair: Pair<String, String> -> User(pair.firsr, pair.second) }
}
```

**Comment by yiyinying** [comment]
It's unnatural to use.

like
private val kodein = Kodein {
        bind<User>() with factory(::User)
}
