### ISSUE TITLE
Proguard com.github.salomonbrys.kodein.TypeTokenKt

### ISSUE THREAD

**Issue by peleteiro** [SalomonBrys/Kodein#8]
Is it safe to ```--dontwarn com.github.salomonbrys.kodein.TypeTokenKt```?

```
Warning: com.github.salomonbrys.kodein.TypeTokenKt: can't find referenced method 'java.lang.String getTypeName()' in library class java.lang.reflect.Type
Warning: there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
```

**Comment by SalomonBrys** [comment]
Absolutely.
This is because Android does not provide Java 8 `getTypeName`. However, this case is handled and an alternative way of getting the type name is used if `getTypeName` does not exist.
So yes, you can safely ignore this warning :smile:
