### ISSUE TITLE
No factory found for bind KClass with Pair as a method factory key

### ISSUE THREAD

**Issue by jdorleans** [SalomonBrys/Kodein#81]
Please, check on the following operations and prints (comments):
```
bind() from multiton { pair: Pair<KClass<*>, Boolean> -> MyClass(pair.first, pair.second) }
// kodein bindings: "bind<MyClass>() with ? { Pair<out KClass<*>, out Boolean> -> ? }" -> 

kodein.with(Pair(otherKClass, bool)).instance<MyClass>() // Exception!
// No factory found for bind<MyClass>() with ? { Pair<out KClass<OtherClass>, out Boolean> -> ? }
```

One more thing... I've created a helper method for `kodein.instance` in order to facilitate the usage on my app. It seems the issue is indeed related to the obj type. Here's what I'm trying to do:

`inline fun <reified T : Any> get(v1: Any, v2: Any) = kodein.with(Pair(v1, v2)).instance<T>()`

I'm not sure why this happens but it seems kodein does not identify the correct binding types. Somehow having v1 and v2 of Any is hiding the correct types.

If I change the types to `get(v1: KClass<*>, v2: Boolean)` it works.

I'd expect the correct type to be identified at runtime.

**Comment by jdorleans** [comment]
Workaround: `kodein.with(Pair(otherKClass as KClass<*>, bool)).instance<MyClass>()`

**Comment by SalomonBrys** [comment]
Unfortunately... wont'fix.

Kodein does try to generify the argument (it will try for `Pair<KClass<OtherClass>, Boolean>` and then for `Pair<*>`), but it does not support "semi-erasure", meaning erasing only part of the generic arguments.
Such a feature would be very complicated, and impact optimization too much for a use case that is quite rare.

I recommend creating a data class specific for this factory.
