### ISSUE TITLE
Does this work with Kotlin native?

### ISSUE THREAD

**Issue by niiamon** [SalomonBrys/Kodein#82]
This notice here is a bit confusing: https://github.com/SalomonBrys/Kodein/tree/master/demo-native

**Comment by SalomonBrys** [comment]
Not yet, it will be as soon as Kotlin Native implements these: https://github.com/SalomonBrys/Kodein/tree/master/kodein-native

**Comment by niiamon** [comment]
@SalomonBrys thanks
