### ISSUE TITLE
Binding Lifecycle?

### ISSUE THREAD

**Issue by thompson4822** [SalomonBrys/Kodein#88]
In Scaldi there was the very handy notion of a lifecycle, where one could define what should happen at the end of the life of a bound instance. Is there something equivalent in Kodein? If not, this would be a really useful addition.

**Comment by SalomonBrys** [comment]
Can you explain what you mean by the end of the life of a bound instance ?
Maybe a documentation link ?

**Comment by thompson4822** [comment]
Here is an example from the Scaldi documentation:

> bind [Server] to new HttpServer initWith (_.init()) destroyWith (_.shutdown())

Basically, defining a destructor when a binding needs cleaned up in a specific way.

**Comment by SalomonBrys** [comment]
Sorry, but Kodein has no plan to support this feature.
There are many features that Kodein relies upon that would be extremely complicated to mantain.

Salomon.
