### ISSUE TITLE
Kodein doesn't throw ClassNotFoundException

### ISSUE THREAD

**Issue by passsy** [SalomonBrys/Kodein#93]
We are using ProGuard and had the following configuration:

```kotlin
val kodein = Kodein {
    bind<PlayerRepository>() with singleton { PlayerRepositoryImpl(instance(), instance()) }
    bind<PlayerStatistic>() with provider { GetPlayerStatistics(instance()) }

    bind<LeagueRepository>() with singleton { LeagueRepositoryImpl(instance(), instance()) }
}
```

throwing following error in line `bind<PlayerStatistic>`:

```
Caused by: com.github.salomonbrys.kodein.Kodein$OverridingException: Binding bind<Object>() with ? { ? } must not override an existing binding.
                      at com.github.salomonbrys.kodein.KodeinContainer$Builder._checkOverrides(KodeinContainer.kt:222)
                      at com.github.salomonbrys.kodein.KodeinContainer$Builder.access$_checkOverrides(KodeinContainer.kt:137)
                      at com.github.salomonbrys.kodein.KodeinContainer$Builder$BindBinder.with(KodeinContainer.kt:273)
                      at com.github.salomonbrys.kodein.Kodein$Builder$TypeBinder.with(Kodein.kt:192)
                      at net.grandcentrix.sportfox.domain.di.DependencyGraphKt$appDataModule$1.invoke(DependencyGraph.kt:105)
                      at net.grandcentrix.sportfox.domain.di.DependencyGraphKt$appDataModule$1.invoke(Unknown Source:6)
```

The interfaces `PlayerRepository` and `PlayerStatistic` actually where unused and therefore removed by ProGuard. Kodin couldn't find the class and made a fallback to `bind<Object>` instead of `bind<PlayerRepository>`. The same with `bind<PlayerStatistic>` which became `bind<Object>` as well throwing the `OverridingException`.

Kodein should first check if the class can be found at all before binding it. Alternatively kodein should disallow bind<Object> at all and print a useful error message. Currently kodein doesn't throw at all when a removed class was added to the graph.

**Comment by passsy** [comment]
To prevent accidental unused mappings we added this check in debug mode to our app:

```kotlin
    /**
     * verify no binding exists for a unused and therefore removed (by ProGuard) class
     */
    @Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN")
    private fun verifyDependencyGraph() {
        if (BuildConfig.DEBUG) {
            try {
                val unused = kodein.instance<Object>()
                throw ClassNotFoundException("a binding exists for a object $unused but the type couldn't be resolved. " +
                        "It therefore got created as binding<Object>. Add a proguard rule to keep the interface or " +
                        "remove the binding from the graph because it seems to be unused.\n" +
                        " See https://github.com/SalomonBrys/Kodein/issues/93 for more details")
            } catch (e: NotFoundException) {
                // all fine, expected that
            }
        }
    }
```

**Comment by SalomonBrys** [comment]
I do not believe that this is Kodein's fault.
As long as Kodein can handle a `Class` object, the type represented by the `Class` object is supposed to be valid.

Are you sure that ProGuard does not itself transform the binding to `bind<Object>()`?

Even if it doesn't, and Kodein somehow does retrieve a `Class` object that is invalid, checking whether the class really exists would mean adding a reflexivity check, which is not optimal for startup performance.

Please feel free to reopen this ticket if you feel this answer is invalid ;)

Salomon.
