### ISSUE TITLE
Push Git tags to see which commit was use to build given version

### ISSUE THREAD

**Issue by szpak** [SalomonBrys/Kodein#95]
There are not Git tags pushed to GitHub. As a result it's hard to determine which commit was used to build a given version (in other words if given fix is (not) available in a particular version).

Sample [commit](https://github.com/SalomonBrys/Kodein/commit/fada162224cfd775d3ad8acf529ac0cb85ae87dc) which (probably) should be a tag.

**Comment by SalomonBrys** [comment]
You're so true.
I've been lazy :(

Sorry about that. I will post tags for every release of version 5.0.
