### ISSUE TITLE
How to make a ViewModel KodeinAware

### ISSUE THREAD

**Issue by sethchhim** [SalomonBrys/Kodein#98]
Android architecture viewModel is bound as:

`bind<ViewModel>() with singleton { ViewModelProviders.of(this@BaseActivity).get(ViewModel::class.java) }`

There is no constructor to pass a kodein instance. How should I approach this so that ViewModel can receive kodein dependencies?

Thanks for any help, your library is great!

**Comment by sethchhim** [comment]
I just initialized it after I bound it.

```

class ViewModel : ViewModel() {

    lateinit var repository: Repository

    fun init(kodein: Kodein) {
        repository = Repository(kodein)
    }

}

viewModel.init(kodein)
```

**Comment by brezinajn** [comment]
You actually can use AndroidViewModel instead of ViewModel.

```Kotlin
class AwesomeViewModel(app: Application): AndroidViewModel(app), KodeinAware{
    override val kodein: Kodein by closestKodein(getApplication<App>())
    private val repository: AwesomeRepository by instance()
}
```
